CREATE TABLE zonas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255),
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_zonas_nombre UNIQUE (nombre)
);

CREATE TABLE mesas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero INTEGER NOT NULL,
    capacidad INTEGER NOT NULL,
    estado VARCHAR(255) NOT NULL DEFAULT 'DISPONIBLE',
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    zona_id BIGINT NOT NULL,
    CONSTRAINT uk_mesas_numero UNIQUE (numero),
    CONSTRAINT fk_mesas_zona FOREIGN KEY (zona_id) REFERENCES zonas (id),
    CONSTRAINT ck_mesas_capacidad_positiva CHECK (capacidad > 0)
);

CREATE INDEX idx_mesas_zona_id ON mesas (zona_id);
