CREATE TABLE reservas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    turno_id BIGINT NOT NULL,
    mesa_id BIGINT NOT NULL,
    fecha DATE NOT NULL,
    inicio TIMESTAMP NOT NULL,
    fin TIMESTAMP NOT NULL,
    cantidad_personas INTEGER NOT NULL,
    estado VARCHAR(20) NOT NULL,
    observaciones VARCHAR(500),
    creado_por_usuario_id BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reservas_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id),
    CONSTRAINT fk_reservas_turno FOREIGN KEY (turno_id) REFERENCES turnos (id),
    CONSTRAINT fk_reservas_mesa FOREIGN KEY (mesa_id) REFERENCES mesas (id),
    CONSTRAINT fk_reservas_creado_por FOREIGN KEY (creado_por_usuario_id) REFERENCES usuarios (id),
    CONSTRAINT ck_reservas_personas_positivas CHECK (cantidad_personas > 0),
    CONSTRAINT ck_reservas_intervalo_valido CHECK (fin > inicio),
    CONSTRAINT ck_reservas_estado CHECK (
        estado IN ('SOLICITADA', 'CONFIRMADA', 'SENTADA', 'FINALIZADA', 'CANCELADA', 'NO_SHOW')
    )
);

CREATE INDEX idx_reservas_mesa_intervalo
    ON reservas (mesa_id, inicio, fin, estado);
CREATE INDEX idx_reservas_turno_fecha
    ON reservas (turno_id, fecha, estado);
CREATE INDEX idx_reservas_cliente_fecha
    ON reservas (cliente_id, fecha, estado);

CREATE TABLE historial_reservas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id BIGINT NOT NULL,
    estado_anterior VARCHAR(20),
    estado_nuevo VARCHAR(20) NOT NULL,
    motivo VARCHAR(500),
    cambiado_por_usuario_id BIGINT NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_historial_reserva FOREIGN KEY (reserva_id) REFERENCES reservas (id),
    CONSTRAINT fk_historial_usuario FOREIGN KEY (cambiado_por_usuario_id) REFERENCES usuarios (id),
    CONSTRAINT ck_historial_estado_anterior CHECK (
        estado_anterior IS NULL OR estado_anterior IN (
            'SOLICITADA', 'CONFIRMADA', 'SENTADA', 'FINALIZADA', 'CANCELADA', 'NO_SHOW'
        )
    ),
    CONSTRAINT ck_historial_estado_nuevo CHECK (
        estado_nuevo IN ('SOLICITADA', 'CONFIRMADA', 'SENTADA', 'FINALIZADA', 'CANCELADA', 'NO_SHOW')
    )
);

CREATE INDEX idx_historial_reserva_fecha
    ON historial_reservas (reserva_id, creado_en);
