CREATE TABLE productos_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    nombre_normalizado VARCHAR(120) NOT NULL,
    descripcion VARCHAR(500),
    precio NUMERIC(12, 2) NOT NULL,
    disponible BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_productos_menu_nombre UNIQUE (nombre_normalizado),
    CONSTRAINT ck_productos_menu_nombre CHECK (CHAR_LENGTH(TRIM(nombre)) > 0),
    CONSTRAINT ck_productos_menu_nombre_normalizado CHECK (nombre_normalizado = LOWER(TRIM(nombre))),
    CONSTRAINT ck_productos_menu_precio CHECK (precio > 0)
);

CREATE INDEX idx_productos_menu_disponible_nombre ON productos_menu (disponible, nombre);
