CREATE TABLE mesas_abiertas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mesa_id BIGINT NOT NULL REFERENCES mesas(id),
    mesa_activa_id BIGINT UNIQUE REFERENCES mesas(id),
    cantidad_personas INTEGER NOT NULL CHECK (cantidad_personas > 0),
    inicio TIMESTAMP NOT NULL,
    fin_previsto TIMESTAMP NOT NULL,
    creada_por_id BIGINT NOT NULL REFERENCES usuarios(id),
    cerrada_por_id BIGINT REFERENCES usuarios(id),
    creada_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cerrada_en TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_mesa_abierta_intervalo CHECK (fin_previsto > inicio),
    CONSTRAINT ck_mesa_abierta_estado CHECK (
        (mesa_activa_id IS NOT NULL AND mesa_activa_id = mesa_id AND cerrada_en IS NULL AND cerrada_por_id IS NULL)
        OR (mesa_activa_id IS NULL AND cerrada_en IS NOT NULL AND cerrada_por_id IS NOT NULL))
);
CREATE INDEX idx_mesas_abiertas_intervalo ON mesas_abiertas(mesa_id, inicio, fin_previsto);

CREATE TABLE pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id BIGINT UNIQUE REFERENCES reservas(id),
    mesa_abierta_id BIGINT UNIQUE REFERENCES mesas_abiertas(id),
    responsable_id BIGINT NOT NULL REFERENCES usuarios(id),
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('ABIERTO','EN_PREPARACION','SERVIDO','CERRADO','CANCELADO')),
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_pedido_origen CHECK (
        (reserva_id IS NOT NULL AND mesa_abierta_id IS NULL) OR
        (reserva_id IS NULL AND mesa_abierta_id IS NOT NULL))
);
CREATE INDEX idx_pedidos_responsable_estado ON pedidos(responsable_id, estado);

CREATE TABLE items_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL REFERENCES pedidos(id),
    producto_menu_id BIGINT NOT NULL REFERENCES productos_menu(id),
    nombre_producto VARCHAR(120) NOT NULL,
    cantidad INTEGER NOT NULL CHECK (cantidad BETWEEN 1 AND 999),
    precio_unitario_historico NUMERIC(12,2) NOT NULL CHECK (precio_unitario_historico > 0)
);
CREATE INDEX idx_items_pedido ON items_pedido(pedido_id);

CREATE TABLE historial_pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL REFERENCES pedidos(id),
    estado_anterior VARCHAR(20),
    estado_nuevo VARCHAR(20) NOT NULL,
    detalle VARCHAR(500) NOT NULL,
    cambiado_por_id BIGINT NOT NULL REFERENCES usuarios(id),
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_historial_pedido_anterior CHECK (estado_anterior IN ('ABIERTO','EN_PREPARACION','SERVIDO','CERRADO','CANCELADO')),
    CONSTRAINT ck_historial_pedido_nuevo CHECK (estado_nuevo IN ('ABIERTO','EN_PREPARACION','SERVIDO','CERRADO','CANCELADO'))
);
CREATE INDEX idx_historial_pedido ON historial_pedidos(pedido_id, id);
