CREATE TABLE feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id BIGINT NOT NULL UNIQUE REFERENCES reservas(id),
    autor_id BIGINT NOT NULL REFERENCES usuarios(id),
    puntuacion INTEGER NOT NULL CHECK (puntuacion BETWEEN 1 AND 5),
    comentario VARCHAR(1000) NOT NULL CHECK (CHAR_LENGTH(TRIM(comentario)) > 0),
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_feedback_autor_fecha ON feedback(autor_id, creado_en);
CREATE INDEX idx_feedback_fecha_puntuacion ON feedback(creado_en, puntuacion);
